[project]
name = "Bash Script"
version = "2.0"

[build]
exclude = [
    "/README.md",
    "/get_words.ts",
    "/.gitignore",
    "/.github/"
]

[[build.buildpacks]]
uri = "heroku/nodejs"

[[build.buildpacks]]
uri = "heroku/python"
