name: Send Data


on:
  schedule:
    # Runs “At 00:00.” every day (see https://crontab.guru)
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  gallary_job:
    runs-on: ubuntu-latest
    name: Sends me the foodle info

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # install the python version needed

      - name: Install requirments
        run: pip install -r github-reqs.txt

      - name: Run Sender
        run: python send_data.py
