name: Send Data


on:
  schedule:
    # Runs “At 00:05.” every day (see https://crontab.guru) slightly delayed so the other workflow has time to run
    - cron: '5 0 * * *'
  workflow_dispatch:


jobs:
  gallary_job:
    runs-on: ubuntu-latest
    name: Sends me the foodle info

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # install the python version needed

      - name: Install requirments
        run: pip install -r github-reqs.txt

      - name: Run Sender
        env:
          PHONENUM: ${{ secrets.PHONENUM }}
          APIKEY: ${{ secrets.APIKEY }}
        run: python send_data.py

